### ISSUE TITLE
wrong file when preview the function code

### ISSUE THREAD

**Issue by virusdefender** [teal-language/vscode-teal#32]
if i press `cmd` and move the cursor to the function name, it will show the type definitions and code preview ([ref](https://stackoverflow.com/questions/52081768/how-i-can-make-ctrl-click-to-go-to-definition-in-visual-studio-code-editor-f)), however it seems the code preview is extract from the current file instead of real file.

`div` function is defined in `main.tl` line 11

![image](https://user-images.githubusercontent.com/4939404/108153028-4ae97d80-7115-11eb-9814-0f5769d905d4.png)

**Comment by pdesaulniers** [comment]
Starting with next `tl` release, function preview should now point to the right file.
