### ISSUE TITLE
syntax highlighting ends when a type is forward declared 

### ISSUE THREAD

**Issue by CoolingTool** [teal-language/vscode-teal#54]
version 0.8.3

![image](https://user-images.githubusercontent.com/62089272/208268289-65557240-d948-454d-a835-e5ace43d8c67.png)
![image](https://user-images.githubusercontent.com/62089272/208268326-c124baa0-9602-4252-b700-db22c302c788.png)

**Comment by pdesaulniers** [comment]
Yes, the grammar does not currently support forward declaration for types. I think it is trying to match an '=' character, but it cannot find one, so the syntax highlighting breaks.

I have attempted a fix. I just need to publish a new release.

**Comment by pdesaulniers** [comment]
This issue should be fixed in v0.8.4. Let me know if you can still reproduce.
