### ISSUE TITLE
Bug: Failed to start on latest vscode version 1.82.0

### ISSUE THREAD

**Issue by hurae** [teal-language/vscode-teal#61]
Visual Studio Code Version: 1.82.0
Known Working Visual Studio Code Version: 1.81.1
Teal Plugin Version: v0.8.3
Platform: Windows 11

Today I updated my vscode version to the latest 1.82.0, then open a tl file, it reports crashed more than 3 times in last five minutes. Although I'm using Windows, I found it won't work on my macbook pro too. The tl code is not changed since the upgrade of vscode, and it compiled with tl cli tool as before.

**Comment by Totto16** [comment]
Same Issue here since 1.82, but using Linux:

Visual Studio Code Version: 1.82.0
Teal Plugin Version: v0.8.3
Platform: Linux - Fedora 38
Teal Compiler Version:  0.15.2


The error the log show is this:
```bash
node:internal/deps/undici/undici:11413
    Error.captureStackTrace(err, this);
          ^

TypeError: Failed to parse URL from /home/myuser/.vscode/extensions/pdesaulniers.vscode-teal-0.8.3/node_modules/web-tree-sitter/tree-sitter.wasm
    at Object.fetch (node:internal/deps/undici/undici:11413:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:399:5)
      at URL.onParseError (node:internal/url:566:9)
      at new URL (node:internal/url:646:5)
      at new Request (node:internal/deps/undici/undici:7002:25)
      at fetch2 (node:internal/deps/undici/undici:10554:25)
      at Object.fetch (node:internal/deps/undici/undici:11411:18)
      at fetch (node:internal/process/pre_execution:248:25)
      at /home/myuser/.vscode/extensions/pdesaulniers.vscode-teal-0.8.3/node_modules/web-tree-sitter/tree-sitter.js:1:15041
      at /home/myuser/.vscode/extensions/pdesaulniers.vscode-teal-0.8.3/node_modules/web-tree-sitter/tree-sitter.js:1:15262
      at /home/myuser/.vscode/extensions/pdesaulniers.vscode-teal-0.8.3/node_modules/web-tree-sitter/tree-sitter.js:1:144 {
    input: '/home/myuser/.vscode/extensions/pdesaulniers.vscode-teal-0.8.3/node_modules/web-tree-sitter/tree-sitter.wasm',
    code: 'ERR_INVALID_URL'
  }
}

Node.js v18.15.0
[Info  - 10:12:03] Connection to server got closed. Server will restart.

```

**Comment by pdesaulniers** [comment]
Thanks for the bug report! I'll take a look at this.

**Comment by pdesaulniers** [comment]
The problem should be fixed in vscode-teal v0.8.4. Can you please confirm? :) 

Between VSCode 1.82.0, Node.js was updated from v16 to v18. This caused some compatibility issues with one of the plugin's dependencies.

**Comment by Totto16** [comment]
Yes it works 👍🏼 🎉 ❤️

**Comment by pdesaulniers** [comment]
Thanks! I'm closing this issue :)
