### ISSUE TITLE
How to properly debug a Teal file?

### ISSUE THREAD

**Issue by lysandre995** [teal-language/vscode-teal#62]
Hi, I was experimenting with Teal code and I was wondering: how to properly debug a Teal file? I tried to create a _main.lua_ file in which I require ([loading teal code from lua](https://github.com/teal-language/tl#loading-teal-code-from-lua)) the external _file.tl_ and then I call a method inside _file.tl_.

If, in the lua file, I put a breakpoint where I call the method and I start the debugger ([using Local Lua Debugger](https://marketplace.visualstudio.com/items?itemName=tomblind.local-lua-debugger-vscode)), when I try to "Step Into" it does it successfully, and I can navigate the content of the Teal method and see correct values of the params, but I simply cannot insert any breakpoint in a Teal file.

Any ideas about can I solve this problem? Other alternative solutions are also appreciated.

**Comment by pdesaulniers** [comment]
Hello! I have never tried using a debugger with Teal. However, someone did mention this extension in Teal's Gitter chat a few months ago:

> Today fun discovery : This VSCode extension https://github.com/tomblind/local-lua-debugger-vscode with the config "scriptFiles": ["${workspaceFolder}/**/*.tl"] in the launch.json and the VSCode settings "debug.allowBreakpointsEverywhere": true, actually works for Teal source files!
I can successfully add breakpoints, run the debugger, play next step, observe variable contents, ...

Perhaps you simply need to set `debug.allowBreakpointsEverywhere` to `true`?

**Comment by lysandre995** [comment]
It works! Thank you!
