### ISSUE TITLE
VSCode teal does not respect `teal.compilerPath.unix` (not tested on windows)

### ISSUE THREAD

**Issue by Frityet** [teal-language/vscode-teal#66]
I am trying to use a custom version of teal, but no matter what I put in that flag, it uses the `tl` in my `$PATH` (from looking at the output in vscode), if I delete `tl` from my `$PATH` it says it cannot find `tl`
```json
{
    "teal.compilerPath.unix": "${workspaceFolder}/extern/experimental/type-narrowing/tl"
}
```

```sh
❯ ./extern/experimental/type-narrowing/tl --version
0.14.1+dev
```

**Comment by Frityet** [comment]
https://github.com/teal-language/vscode-teal/blob/f8116b24ce8fd93626a56a606c5a8aeaa13e3d44/server/teal.ts#L185

it seems like this flag isn't used?

**Comment by pdesaulniers** [comment]
Yes, this flag was removed at some point. I've explained my reasoning here: https://github.com/teal-language/vscode-teal/issues/42#issuecomment-86904050

> The extension used to have an option for customizing the compiler path, but it would lead to some issues due to how LUA_PATH works.
>
> The tl driver always require the first tl.lua that it finds in the LUA_PATH. Even if we call /subdirectory/tl/tl directly, this doesn't mean that the driver will necessarily pick up /subdirectory/tl/tl.lua. It could pick a different one, say, /usr/local/lua/tl.lua instead. So, the tl.compilerPath option did not behave as expected in some cases :/

With that said, it seems like tl now has some code to handle this use-case, so I don't mind re-adding the flag: https://github.com/teal-language/tl/blob/cecb87d666aa38eaf2f9fb2ca7de0306481f3756/tl#L3-L15

**Comment by Frityet** [comment]
> Yes, this flag was removed at some point. I've explained my reasoning here: [#42 (comment)](https://github.com/teal-language/vscode-teal/issues/42#issuecomment-86904050)
> 
> > The extension used to have an option for customizing the compiler path, but it would lead to some issues due to how LUA_PATH works.
> > The tl driver always require the first tl.lua that it finds in the LUA_PATH. Even if we call /subdirectory/tl/tl directly, this doesn't mean that the driver will necessarily pick up /subdirectory/tl/tl.lua. It could pick a different one, say, /usr/local/lua/tl.lua instead. So, the tl.compilerPath option did not behave as expected in some cases :/
> 
> With that said, it seems like tl now has some code to handle this use-case, so I don't mind re-adding the flag: https://github.com/teal-language/tl/blob/cecb87d666aa38eaf2f9fb2ca7de0306481f3756/tl#L3-L15

THANK YOU SO MUCH!!!! I HAVE BEEN SPENDING THE LAST FEW HOURS TRYING TO RE-ADD THE FLAG MYSELF BUT NODE WAS KILLING ME!!

**Comment by Frityet** [comment]
Consistent across multiple tl versions:
```toml
tl version: 0.15.2
[Error] tl version is null
[Error] tl version is null
[Error] tl version is null
[Error] tl version is null
[Error] tl version is null
[Error] tl version is null
[Error] tl version is null
```

**Comment by pdesaulniers** [comment]
In your case, I assume it throws one error per opened document?

I think it should be fixed by https://github.com/teal-language/vscode-teal/commit/92d83469f863b5092605e34f1f519c62e7359660, can you please confirm?

**Comment by Frityet** [comment]
Will do, give me a min to compile

**Comment by Frityet** [comment]
Works like a charm!

**Comment by pdesaulniers** [comment]
Great, thanks! I will now publish version 0.9.0 on the marketplace :)
