### ISSUE TITLE
Code uses 100% CPU on file edit

### ISSUE THREAD

**Issue by V1K1NGbg** [teal-language/vscode-teal#70]
### Issue:
Hello, I have encountered an issue with the tl extension where when I make even the slightest change in a tl file, VS code ramps up to 100% CPU usage and the only solution I have found is to kill the process.

### Set up:
I am currently using the `next` branch of `teal`, and I am working on the `lua-to-teal-migration` branch of `luarocks`.

### Some more info:
vs code version: 1.91.1
lua version: 5.4.7
teal version: 0.15.3+dev
tl extention version: 0.9.0

### EDIT:
I have tested it on two machines and with only the tl extension enabled

Happy to provide more info if needed!

### EDIT 2:
Another thing I have noticed is that the problem occures only when editing `.tl` files (`d.tl` files are unaffected as well as `.lua` files)

Also the process name that does this uses `/out/server/server.js` if that helps

**Comment by hishamhm** [comment]
I've tested this and was able to reproduce it locally by installing VSCode and the extension, fetching the `lua-to-teal-migration` of the LuaRocks repo, and then editing any `.tl` file. After a few edits, a `code` process goes to constant 100% CPU. Killing it makes the extension resume working, until the next edits/save, when the CPU starts spinning again.

Unfortunately, I don't know enough about the VSCode extension architecture to propose a solution (I tried blindly tweaking the constant in a `throttle(250, ...)` call to a higher number I didn't strike any luck there).

**Comment by pdesaulniers** [comment]
I can reproduce the issue. It seems like `symbolsInScope` is going into an infinite loop...

**Comment by pdesaulniers** [comment]
@hishamhm I can reproduce the issue with plain `tl` as well:

```sh
tl types -p 29,24 src/luarocks/fetch/git_ssh.tl
```

This causes an infinite loop on my machine. The stack traceback mentions `tl.symbols_in_scope`

**Comment by V1K1NGbg** [comment]
fixed by the latest commit in  [next](https://github.com/teal-language/tl/tree/next)
