### ISSUE TITLE
Formatter

### ISSUE THREAD

**Issue by apiel** [teal-language/vscode-teal#76]
Is there any way to get formatting for teal files in vscode?

**Comment by pdesaulniers** [comment]
Hello! Unfortunately, I'm not currently aware of any code formatting tool for Teal code. This would be pretty useful.

**Comment by apiel** [comment]
It's a pity. Teal seem promising but still far from convenient to use. I was searching for a statically type language for my C application and as Lua is super easy to integrate using Teal was a great option. However, not having proper integration with VScode is a deal breaker for me. I endup still to keep lua and now use `lua-language-server` for type checking and it does pretty good job actually, at least good enough for my needs.
